-define(MANAGER_NAMES, [
	alpha_manager,
	beta_manager,
	gamma_manager,
	delta_manager,
	epsilon_manager,
	zeta_manager,
	eta_manager,
	theta_manager,
	iota_manager,
	kappa_manager,
	lambda_manager,
	mu_manager,
	nu_manager,
	xi_manager,
	omicron_manager,
	pi_manager,
	rho_manager,
	sigma_manager,
	tau_manager,
	upsilon_manager,
	phi_manager,
	chi_manager,
	psi_manager,
	omega_manager]).
-define(MANAGER_NAMES_LENGTH, 24).